(ns app.domain.frontend.expenses.events.articles
  "Articles domain events — CRUD generated by event factory,
  related-records modal generated by related-records factory."
  (:require
    [app.domain.frontend.expenses.events.entity-configs :as configs]
    [app.domain.frontend.expenses.events.events-factory :as factory]
    [app.domain.frontend.expenses.events.related-records-factory :as rr-factory]))

;; Standard CRUD events for articles
(factory/register-entity-events! configs/articles-config)

;; Related-records modal events
(rr-factory/register-related-records-events!
  {:entity-key :articles
   :base-path [:admin :expenses :articles]
   :api-endpoint "/admin/api/expenses/articles"
   :valid-related-types #{"expenses" "receipts" "providers" "stores" "manufacturers" "subcategories"}
   :default-limit 200})
