(ns app.domain.frontend.expenses.subs.articles
  (:require
    [app.domain.frontend.expenses.subs.related-records-factory :as rr-factory]
    [re-frame.core :as rf]))

(def ^:private base-path [:admin :expenses :articles])

(rf/reg-sub
  :expenses/articles
  (fn [db _]
    (get-in db (conj base-path :items))))

;; Related-records modal subscriptions (generated by factory).
;; Registers keywords like :expenses/article-related-records-modal-open?,
;; :expenses/article-related-records-modal-entity, :expenses/article-related-records-step, etc.
(rr-factory/register-related-records-subs!
  {:entity-singular "article"
   :base-path base-path})
