#!/usr/bin/env bb
;; Legacy Inventory Audit (Babashka)
;;
;; Compares the current inventory (generated by scripts/legacy/inventory.bb)
;; against a baseline EDN file (default: resources/legacy-inventory.edn).
;;
;; Exit codes:
;; - 0: OK (no new legacy occurrences)
;; - 1: New legacy occurrences found (or strict mode violated)
;; - 2+: Unexpected error
;;
;; Usage:
;;   bb scripts/legacy/audit.bb
;;   bb scripts/legacy/audit.bb --strict
;;   bb scripts/legacy/audit.bb --baseline resources/legacy-inventory.edn
;;   bb scripts/legacy/audit.bb --category settings-schema-legacy

(ns scripts.legacy.audit
  (:require
   [babashka.fs :as fs]
   [clojure.edn :as edn]
   [clojure.java.shell :as sh]
   [clojure.string :as str]))

(defn- parse-args [args]
  (loop [m {:baseline "resources/legacy-inventory.edn"
            :strict false
            :category nil}
         xs args]
    (if-let [a (first xs)]
      (cond
        (= a "--strict") (recur (assoc m :strict true) (next xs))
        (or (= a "--baseline") (= a "-b")) (recur (assoc m :baseline (second xs)) (nnext xs))
        (= a "--category") (recur (assoc m :category (second xs)) (nnext xs))
        :else (recur m (next xs)))
      m)))

(defn- safe-read-edn-string [s]
  (when (some? s)
    (let [s (str/trim s)]
      (when-not (str/blank? s)
        (edn/read-string s)))))

(defn- read-baseline [path]
  (if (fs/exists? path)
    (safe-read-edn-string (slurp path))
    []))

(defn- run-current-inventory []
  (let [{:keys [exit out err]} (sh/sh "bb" "scripts/legacy/inventory.bb")]
    (when-not (zero? exit)
      (binding [*out* *err*]
        (println "Failed to run inventory generator:"))
      (binding [*out* *err*]
        (println err))
      (throw (ex-info "inventory.bb failed" {:exit exit :err err})))
    (or (safe-read-edn-string out) [])))

(defn- item->key [m]
  ;; Stable identity for an occurrence. Intentionally does NOT include :line,
  ;; since line numbers can shift during refactors without changing behavior.
  (let [code (or (:match m) (:code m) "")]
    [(:category m) (:file m) (:pattern m) code]))

(defn- matches-category? [category m]
  (if (nil? category)
    true
    (= (keyword category) (:category m))))

(defn -main [& args]
  (try
    (let [{:keys [baseline strict category]} (parse-args (vec args))
          baseline-items (vec (or (read-baseline baseline) []))
          current-items (->> (run-current-inventory)
                             (filter (partial matches-category? category))
                             vec)
          baseline-keys (set (map item->key baseline-items))
          new-items (->> current-items
                         (remove (fn [m] (contains? baseline-keys (item->key m))))
                         vec)
          baseline-count (count baseline-items)
          current-count (count current-items)
          new-count (count new-items)]

      (println "Legacy audit")
      (println "  baseline:" baseline "(" baseline-count "items )")
      (when category
        (println "  category:" category))
      (println "  current:  (" current-count "items )")
      (println "  new:      (" new-count "items )")

      (cond
        strict
        (if (zero? current-count)
          (do
            (println "OK: strict mode and inventory is empty")
            (System/exit 0))
          (do
            (binding [*out* *err*]
              (println "FAIL: strict mode requires zero legacy items; found" current-count))
            (System/exit 1)))

        (zero? new-count)
        (do
          (println "OK: no new legacy occurrences")
          (System/exit 0))

        :else
        (do
          (binding [*out* *err*]
            (println "FAIL: new legacy occurrences detected:" new-count)
            (doseq [m (take 100 new-items)]
              (println
               (str "- " (:file m) ":" (:line m)
                    "  " (name (:category m))
                    "  pattern=" (pr-str (:pattern m))
                    "  code=" (pr-str (or (:match m) (:code m) "")))))
            (when (> new-count 100)
              (println (str "... and " (- new-count 100) " more"))))
          (System/exit 1))))

    (catch Exception e
      (binding [*out* *err*]
        (println "Legacy audit crashed:" (.getMessage e)))
      (System/exit 2))))

(apply -main *command-line-args*)
