-- No-op: onboarding tables are now created by 0053_receipt_file_purged_at.edn
-- (automigrate .edn migration). This file was originally the canonical creator,
-- but .sql migrations are invisible to automigrate's state model, causing
-- duplicate create-table errors. Kept as a no-op so existing DBs that already
-- applied it don't break.
