(ns app.template.frontend.auto-test-models
  "Inline database models for frontend test data generation.")

(def models
  {:tenants {:fields [[:id :uuid {:primary-key true :default [:gen_random_uuid]}]
                      [:name [:varchar 255] {:null false}]
                      [:slug [:varchar 100] {:null false :unique true}]
                      [:status [:enum :tenant-status] {:null false :default "active"}]
                      [:settings :jsonb {:default {}}]
                      [:subscription_tier [:enum :subscription-tier] {:default "free"}]
                      [:subscription_status [:enum :subscription-status] {:default "trialing"}]
                      [:trial_ends_at :timestamptz]
                      [:billing_email [:varchar 255]]
                      [:stripe_customer_id [:varchar 255] {:unique true}]
                      [:stripe_subscription_id [:varchar 255]]
                      [:created_at :timestamptz {:default [:now]}]
                      [:updated_at :timestamptz {:default [:now]}]]
             :types [[:tenant-status :enum {:choices ["active" "suspended" "cancelled"]}]
                     [:subscription-tier :enum {:choices ["free" "starter" "professional" "enterprise"]}]
                     [:subscription-status :enum {:choices ["trialing" "active" "past_due" "cancelled"]}]]}
   :users {:fields [[:id :uuid {:primary-key true :default [:gen_random_uuid]}]
                    [:tenant_id :uuid {:foreign-key :tenants/id :null false :on-delete :cascade}]
                    [:email [:varchar 255] {:null false}]
                    [:full_name [:varchar 255]]
                    [:avatar_url :text]
                    [:auth_provider [:enum :auth-provider] {:null false}]
                    [:provider_user_id [:varchar 255]]
                    [:role [:enum :user-role] {:null false :default "member"}]
                    [:status [:enum :user-status] {:null false :default "active"}]
                    [:last_login_at :timestamptz]
                    [:created_at :timestamptz {:default [:now]}]
                    [:updated_at :timestamptz {:default [:now]}]]
           :types [[:auth-provider :enum {:choices ["google" "email" "apple"]}]
                   [:user-role :enum {:choices ["owner" "admin" "member" "viewer"]}]
                   [:user-status :enum {:choices ["active" "inactive" "suspended"]}]]}
   :properties {:fields [[:id :uuid {:primary-key true :default [:gen_random_uuid]}]
                         [:tenant_id :uuid {:foreign-key :tenants/id :null false :on-delete :cascade}]
                         [:owner_id :uuid {:foreign-key :users/id :null false :on-delete :cascade}]
                         [:name [:varchar 255] {:null false}]
                         [:address :text]
                         [:property_type [:enum :property-type] {:default "apartment"}]
                         [:status [:enum :property-status] {:default "active"}]
                         [:settings :jsonb {:default {}}]
                         [:financial_settings :jsonb {:default {}}]
                         [:created_at :timestamptz {:default [:now]}]
                         [:updated_at :timestamptz {:default [:now]}]]
                :types [[:property-type :enum {:choices ["apartment" "house" "room" "commercial" "other"]}]
                        [:property-status :enum {:choices ["active" "inactive" "archived"]}]]}
   :transaction_types {:fields [[:id :uuid {:primary-key true :default [:gen_random_uuid]}]
                                [:tenant_id :uuid {:foreign-key :tenants/id :on-delete :cascade}]
                                [:name [:varchar 255] {:null false}]
                                [:flow [:enum :flow] {:null false}]
                                [:is_global :boolean {:default false}]
                                [:parent_category_id :uuid {:foreign-key :transaction_types/id}]
                                [:icon [:varchar 50]]
                                [:color [:varchar 7]]
                                [:created_at :timestamptz {:default [:now]}]
                                [:updated_at :timestamptz {:default [:now]}]]
                       :types [[:flow :enum {:choices ["income" "expense"]}]]}
   :transactions {:fields [[:id :uuid {:primary-key true :default [:gen_random_uuid]}]
                           [:tenant_id :uuid {:foreign-key :tenants/id :null false :on-delete :cascade}]
                           [:property_id :uuid {:foreign-key :properties/id :on-delete :cascade}]
                           [:transaction_type_id :uuid {:foreign-key :transaction_types/id :null false}]
                           [:description :text {:null false :check [:> [:length :description] 3]}]
                           [:amount [:decimal 15 2] {:null false :check [:> :amount 0]}]
                           [:date :date {:null false}]
                           [:paid_by_user_id :uuid {:foreign-key :users/id :on-delete :set-null}]
                           [:tags :jsonb {:default []}]
                           [:attachments :jsonb {:default []}]
                           [:metadata :jsonb {:default {}}]
                           [:created_by :uuid {:foreign-key :users/id :null false :on-delete :cascade}]
                           [:updated_by :uuid {:foreign-key :users/id :on-delete :set-null}]
                           [:created_at :timestamptz {:default [:now]}]
                           [:updated_at :timestamptz {:default [:now]}]]}})
